const fruits = ['Apple','Mango','Banana']

// fruits[1]
// console.log("\n")
// fruits.forEach((item)=>{console.log(item)})
// console.log("\n")
// fruits.push("Orange")
// console.log("\n")
// //fruits.shift(1)
// fruits.splice(0,1)
// console.log("\n")
// fruits.unshift("Grapes")
// console.log("\n")
// fruits.pop()
// console.log("\n")
// const fruits2 = fruits.concat(['Cherry','Peach'])
// console.log("\n")
// fruits.splice(1,1) //for now Mango is at second pos
// console.log("\n")
// fruits.splice(1,0,"Pineapple")
// console.log("\n")
// const fruits3 =fruits.slice(0,2)
// console.log("\n")
// fruits.splice(1,0,"Mango")
// fruits.indexOf("Mango")
// console.log("\n")
// fruits.includes("Banana")
// console.log("\n")
// console.log(fruits.find((index) => index[0] === 'M'))
// console.log("\n")
// const temp = fruits.filter((value)=>{return value.length>5?value:null})
// console.log("\n")
// fruits.sort()
// console.log("\n")
// fruits.reverse()
// console.log("\n")
// abc = fruits.reduce((total,value)=> {return total.concat(", "+value)})
// console.log(abc)
// console.log("\n")
// const fruitmap = fruits.map((value)=>{return value.toUpperCase()})
// console.log(fruitmap)
// console.log("\n")
// fruits.unshift("Kiwi")
// fruits.splice(fruits.indexOf("Mango"),1)
// fruits.sort()
// console.log("\n")
// const array = [1,[2,3],[4,[5,6]]]
// console.log(array.flat(2))
// let fruitstr = fruits.join("-")
// console.log("/n")